function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	AddTextEntry("NSPEEDO", "Speedo Express")
	AddTextEntry("0x6BD9D2BC", "Rear Ladder & Rear Panels")
	AddTextEntry("0x01AD54FE", "Rear Steps")
	AddTextEntry("0x495DB90A", "Side Steps")
	AddTextEntry("0xEAE6F78D", "Roof Racks")
	AddTextEntry("0x65AD732B", "Chrome Bull Bar I")
	AddTextEntry("0x8D58B64C", "Chrome Bull Bar II")
	AddTextEntry("0xDC17D3C9", "Chrome Bull Bar I w/ Round Lights")
	AddTextEntry("0xA9ED6F75", "Chrome Bull Bar II w/ Round Lights")
	AddTextEntry("0x2D0D81EC", "Light Bar Mount")
	AddTextEntry("0x12F81AA3", "LED Light Bar")
	AddTextEntry("0x3E532477", "Plastic Push Bar I")
	AddTextEntry("0x674EACC2", "Plastic Push Bar II")
	AddTextEntry("0x3D08D837", "Plastic Push Bar I w/ LED Light Bar")
	AddTextEntry("0x4AB2F38B", "Plastic Push Bar II w/ LED Light Bar")
	AddTextEntry("0x1927DA21", "Extended Chrome Bull Bar I")
	AddTextEntry("0x027F1623", "Extended Chrome Bull Bar I w/ Round Lights")
	AddTextEntry("0x2AC67D5E", "Plastic Push Bar III")
	AddTextEntry("0x3115C2EB", "Extended Plastic Push Bar III")
	AddTextEntry("0xB11A42F2", "Extended Plastic Push Bar III w/ Light Guards")
	AddTextEntry("0x74645676", "Chrome Ram-Bar")
	AddTextEntry("0x0D64D3B9", "Chrome Ram-Bar w/ LED Light Bar")
	AddTextEntry("0xC75FC7A0", "Chrome Ram-Bar w/ Round Lights")
	AddTextEntry("0x7F9E6CEA", "Plastic Ram-Bar")
	AddTextEntry("0x5965B5FE", "Plastic Ram-Bar w/ LED Light Bar")
	AddTextEntry("0x360C6F4C", "Plastic Ram-Bar w/ Round Lights")
	AddTextEntry("0xA604773E", "Plastic Rear Step")
	AddTextEntry("0xE12FED94", "Chrome Rear Step")
	AddTextEntry("0x82773024", "Extended Chrome Rear Step")
	AddTextEntry("0x98FF5D30", "Plastic Pipe Rear Step")
	AddTextEntry("0xA604773E", "Mesh Grille w/ Plastic Surround")
	AddTextEntry("0xE12FED94", "Mesh Grille w/ Chrome Surround")
	AddTextEntry("0x82773024", "Debadged Mesh Grille w/ Chrome Surround")
	AddTextEntry("0x98FF5D30", "Debadged Mesh Grille w/ Plastic Surround")
	AddTextEntry("0xC022BBCD", "Chrome Mesh Grille w/ Plastic Surround")
	AddTextEntry("0xE553A777", "Chrome Mesh Grille w/ Chrome Surround")
	AddTextEntry("0xFB8A26E9", "Debadged Chrome Mesh Grille w/ Chrome Surround")
	AddTextEntry("0xC34D5E6E", "Debadged Chrome Mesh Grille w/ Plastic Surround")
	AddTextEntry("0x5BA2F2CB", "Chrome Stock Grille w/ Plastic Surrounds")
	AddTextEntry("0x06762C74", "Chrome Stock Grille w/ Chrome Surrounds")
	AddTextEntry("0x2845D955", "Debadged Chrome Stock Grille w/ Chrome Surrounds")
	AddTextEntry("0xA9AC87EE", "Debadged Chrome Stock Grille w/ Plastic Surrounds")
	AddTextEntry("0x2EEC995F", "Stock Grille w/ Chrome Surrounds")
	AddTextEntry("0xE15B647A", "Debadged Stock Grille w/ Chrome Surrounds")
	AddTextEntry("0xFC3D3401", "Custom Grille w/ Plastic Surround")
	AddTextEntry("0x5EAAEA0B", "Custom Grille w/ Chrome Surround")
	AddTextEntry("0xCC1E5684", "Debadged Custom Grille w/ Chrome Surround")
	AddTextEntry("0x642C06B1", "Custom Grille w/ Chrome Surround & Intercooler Setup")
	AddTextEntry("0xEA557402", "Debadged Custom Grille w/ Plastic Surround")
	AddTextEntry("0xCAA9B4AF", "Custom Grille w/ Plastic Surround & Intercooler Setup")
	AddTextEntry("0x857363CD", "Debadged Stock Grille")
	AddTextEntry("0xE92E180A", "Rear Door Window Panels w/ Rear Ladder")
	AddTextEntry("0x8059E184", "Rear Door Ladder")
	AddTextEntry("0xAB9FB01B", "Rear Door Window Panels")
	AddTextEntry("0x296F815F", "Roof Rack I")
	AddTextEntry("0x7637BA61", "Roof Rack I w/ Construction Equipment I")
	AddTextEntry("0x1F878D0E", "Roof Rack I w/ Construction Equipment II")
	AddTextEntry("0x3B502520", "Roof Rack II w/ Construction Equipment I")
	AddTextEntry("0x54A52520", "Roof Rack II w/ Construction Equipment II")
	AddTextEntry("0x99696151", "Roof Rack III")
	AddTextEntry("0x36F1CD80", "Roof Rack III w/ Construction Equipment I")
	AddTextEntry("0xB09BC0D6", "Roof Rack III w/ Solar Panels")
	AddTextEntry("0xABBC05F2", "Off-Road Roof Rack")
	AddTextEntry("0x79B2C4CC", "Off-Road Roof Rack w/ Light Bar Mount")
	AddTextEntry("0x74BEBAE4", "Off-Road Roof Rack w/ LED Light Bar")
	AddTextEntry("0x67011F69", "Off-Road Roof Rack w/ Round Lights")
	AddTextEntry("0x5243F5EF", "Off-Road Roof Rack w/ Side Ladder")
	AddTextEntry("0x427D5662", "Off-Road Roof Rack w/ Supplies I")
	AddTextEntry("0xD8BB2728", "Off-Road Roof Rack w/ Supplies I & Side Ladder")
	AddTextEntry("0x1D970C96", "Off-Road Roof Rack w/ Supplies II")
	AddTextEntry("0x3B48D045", "Off-Road Roof Rack w/ Supplies II & Side Ladder")
	AddTextEntry("0x07DEE122", "Off-Road Roof Rack w/ Light Bar Mount & Side Ladder")
	AddTextEntry("0xDF0D8F74", "Off-Road Roof Rack w/ Light Bar Mount & Supplies I")
	AddTextEntry("0x3EFCFDAF", "Off-Road Roof Rack w/ Light Bar Mount, Supplies I & Side Ladder")
	AddTextEntry("0xC8C362E0", "Off-Road Roof Rack w/ Light Bar Mount & Supplies II")
	AddTextEntry("0xC5411C4C", "Off-Road Roof Rack w/ Light Bar Mount, Supplies II & Side Ladder")
	AddTextEntry("0xC2C629DF", "Off-Road Roof Rack w/ LED Light Bar & Side Ladder")
	AddTextEntry("0xB47E8D50", "Off-Road Roof Rack w/ LED Light Bar & Supplies I")
	AddTextEntry("0xDD8F6F3B", "Off-Road Roof Rack w/ LED Light Bar, Supplies I & Side Ladder")
	AddTextEntry("0x987F5552", "Off-Road Roof Rack w/ LED Light Bar & Supplies II")
	AddTextEntry("0x29814483", "Off-Road Roof Rack w/ LED Light Bar & Supplies II")
	AddTextEntry("0x4342AAE2", "Off-Road Roof Rack w/ Round Lights & Side Ladder")
	AddTextEntry("0x7DAC9FAD", "Off-Road Roof Rack w/ Round Lights & Supplies I")
	AddTextEntry("0xC9B66B6D", "Off-Road Roof Rack w/ Round Lights, Supplies I & Side Ladder")
	AddTextEntry("0xA76BF32B", "Off-Road Roof Rack w/ Round Lights & Supplies II")
	AddTextEntry("0x42AEDC3E", "Off-Road Roof Rack w/ Round Lights, Supplies II & Side Ladder")
	AddTextEntry("0x0435B37B", "Front Splitter")
	AddTextEntry("0x6F83A017", "Plastic Side Step")
	AddTextEntry("0x6A161538", "Plastic Extended Side Step")
	AddTextEntry("0x7C0F392A", "Chrome Side Step")
	AddTextEntry("0x366A2DE1", "Chrome Extended Side Step")
	AddTextEntry("0x467CCE06", "Slat Side Step")
--[[

--]]	
end)